name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          a4sync-tools/target/a4sync-tools-*.jar
          a4sync-server/target/a4sync-server-*.jar
        draft: true
        prerelease: false
        generate_release_notes: true